name: Daily Docker Build
on:
  workflow_dispatch:
  schedule:
    - cron: '00 03 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      TZ: 'Asia/Tokyo'
      IMAGE_NAME: tw-search-retweet-bot
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt && \
          yarn install --network-concurrency 1
      - name: Run Test
        run: make test
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Get latest version tag
        id: latest_tag
        run: |
          hashtag="$(git rev-parse HEAD|cut -c 1-7)"
          echo "::set-output name=hashtag::${hashtag}"
          daily="$(date '+%Y%m%d%H%M%S')"
          echo "::set-output name=daily::${daily}"
      - name: Build and push
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:daily
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.latest_tag.outputs.hashtag }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.latest_tag.outputs.daily }}
